### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tcpipchip** [hallard/RAK3172-Breakout#4] opened 2022-10-25 00:57 UTC
![image](https://user-images.githubusercontent.com/11488460/197657663-a91842c5-e621-445b-a03b-83b85986134b.png)
Hi
can you help me about this error ?
Thanks
I followed your instructions
https://github.com/hallard/RAK3172-Breakout#readme
thanks!!!

**Comment by hallard** [comment] 2022-10-25 14:12
duplicate of https://github.com/ARMmbed/stm32customtargets/issues/35 
I'm closing this one

**Closed as completed by hallard** 2022-10-25 14:12 UTC
